[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_ENV_MODE = "production"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200